"""init

Revision ID: 5bfa5098a3e6
Revises: 
Create Date: 2025-11-26 19:54:33.635139

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bfa5098a3e6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('personality', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('avatar', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('voice_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('speech_rate', sa.Float(), nullable=True),
    sa.Column('pitch', sa.Float(), nullable=True),
    sa.Column('default_emotion', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('enabled_emotions', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_interaction_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_characters_active', 'characters', ['is_active'], unique=False)
    op.create_index('idx_characters_default', 'characters', ['is_default'], unique=False)
    op.create_index(op.f('ix_characters_is_active'), 'characters', ['is_active'], unique=False)
    op.create_index(op.f('ix_characters_is_default'), 'characters', ['is_default'], unique=False)
    op.create_index(op.f('ix_characters_name'), 'characters', ['name'], unique=True)
    op.create_table('config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mode', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gpu_layers', sa.Integer(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('max_tokens', sa.Integer(), nullable=False),
    sa.Column('openai_api_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('anthropic_api_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('conversation_memory_length', sa.Integer(), nullable=False),
    sa.Column('emotion_confidence_threshold', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_config_mode', 'config', ['id'], unique=False)
    op.create_table('vrmmodelcache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('vrm_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('thumbnail_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('blendshape_count', sa.Integer(), nullable=False),
    sa.Column('blendshape_names', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=False),
    sa.Column('load_time_ms', sa.Integer(), nullable=False),
    sa.Column('last_used', sa.DateTime(), nullable=False),
    sa.Column('use_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cache_usage', 'vrmmodelcache', ['last_used'], unique=False)
    op.create_index(op.f('ix_vrmmodelcache_file_hash'), 'vrmmodelcache', ['file_hash'], unique=True)
    op.create_index(op.f('ix_vrmmodelcache_file_path'), 'vrmmodelcache', ['file_path'], unique=True)
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_activity', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_conversations_active', 'conversations', ['last_activity', 'character_id'], unique=False)
    op.create_index(op.f('ix_conversations_character_id'), 'conversations', ['character_id'], unique=False)
    op.create_index(op.f('ix_conversations_is_active'), 'conversations', ['is_active'], unique=False)
    op.create_table('emotionkeywords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('emotion', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('keyword', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_keyword_lookup', 'emotionkeywords', ['character_id', 'keyword', 'language'], unique=False)
    op.create_index(op.f('ix_emotionkeywords_character_id'), 'emotionkeywords', ['character_id'], unique=False)
    op.create_index(op.f('ix_emotionkeywords_emotion'), 'emotionkeywords', ['emotion'], unique=False)
    op.create_index(op.f('ix_emotionkeywords_keyword'), 'emotionkeywords', ['keyword'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(length=20000), nullable=False),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('emotion', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('emotion_confidence', sa.Float(), nullable=False),
    sa.Column('ai_detected_emotion', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('generation_time_ms', sa.Integer(), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('emotionlogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('emotion', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('trigger_source', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_emotion_timeseries', 'emotionlogs', ['timestamp', 'emotion'], unique=False)
    op.create_index(op.f('ix_emotionlogs_conversation_id'), 'emotionlogs', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_emotionlogs_emotion'), 'emotionlogs', ['emotion'], unique=False)
    op.create_index(op.f('ix_emotionlogs_message_id'), 'emotionlogs', ['message_id'], unique=False)
    op.create_index(op.f('ix_emotionlogs_timestamp'), 'emotionlogs', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_emotionlogs_timestamp'), table_name='emotionlogs')
    op.drop_index(op.f('ix_emotionlogs_message_id'), table_name='emotionlogs')
    op.drop_index(op.f('ix_emotionlogs_emotion'), table_name='emotionlogs')
    op.drop_index(op.f('ix_emotionlogs_conversation_id'), table_name='emotionlogs')
    op.drop_index('idx_emotion_timeseries', table_name='emotionlogs')
    op.drop_table('emotionlogs')
    op.drop_table('messages')
    op.drop_index(op.f('ix_emotionkeywords_keyword'), table_name='emotionkeywords')
    op.drop_index(op.f('ix_emotionkeywords_emotion'), table_name='emotionkeywords')
    op.drop_index(op.f('ix_emotionkeywords_character_id'), table_name='emotionkeywords')
    op.drop_index('idx_keyword_lookup', table_name='emotionkeywords')
    op.drop_table('emotionkeywords')
    op.drop_index(op.f('ix_conversations_is_active'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_character_id'), table_name='conversations')
    op.drop_index('idx_conversations_active', table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_vrmmodelcache_file_path'), table_name='vrmmodelcache')
    op.drop_index(op.f('ix_vrmmodelcache_file_hash'), table_name='vrmmodelcache')
    op.drop_index('idx_cache_usage', table_name='vrmmodelcache')
    op.drop_table('vrmmodelcache')
    op.drop_index('idx_config_mode', table_name='config')
    op.drop_table('config')
    op.drop_index(op.f('ix_characters_name'), table_name='characters')
    op.drop_index(op.f('ix_characters_is_default'), table_name='characters')
    op.drop_index(op.f('ix_characters_is_active'), table_name='characters')
    op.drop_index('idx_characters_default', table_name='characters')
    op.drop_index('idx_characters_active', table_name='characters')
    op.drop_table('characters')
    # ### end Alembic commands ###
