"""init

Revision ID: 6ce2d88f27b7
Revises: 
Create Date: 2025-11-29 13:13:08.825070

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ce2d88f27b7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('personality', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('avatar', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('vrm_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role_in_world', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('world_context', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('speech_pattern', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('favorite_phrases_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sentence_length_preference', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('response_length_default', sa.Integer(), nullable=True),
    sa.Column('ask_questions_frequency', sa.Float(), nullable=False),
    sa.Column('emoticons_frequency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('memory_retention_preference', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('default_emotion', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('enabled_emotions_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('voice_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('speech_rate', sa.Float(), nullable=True),
    sa.Column('pitch', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_interaction_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_character_active', 'character', ['is_active'], unique=False)
    op.create_index('idx_character_default', 'character', ['is_default'], unique=False)
    op.create_index(op.f('ix_character_name'), 'character', ['name'], unique=True)
    op.create_table('config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mode', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gpu_layers', sa.Integer(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('max_tokens', sa.Integer(), nullable=False),
    sa.Column('openai_api_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('anthropic_api_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('conversation_memory_length', sa.Integer(), nullable=False),
    sa.Column('emotion_confidence_threshold', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_config_mode', 'config', ['id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gender', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('profile_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('conversation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('relationship_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_intent', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('world_state', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_activity', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_conversation_activity', 'conversation', ['last_activity', 'character_id'], unique=False)
    op.create_index(op.f('ix_conversation_character_id'), 'conversation', ['character_id'], unique=False)
    op.create_index(op.f('ix_conversation_is_active'), 'conversation', ['is_active'], unique=False)
    op.create_index(op.f('ix_conversation_user_id'), 'conversation', ['user_id'], unique=False)
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(length=20000), nullable=False),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('emotion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('emotion_confidence', sa.Float(), nullable=True),
    sa.Column('emotion_intensity', sa.Float(), nullable=False),
    sa.Column('ai_detected_emotion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('generation_time_ms', sa.Integer(), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_emotion'), 'message', ['emotion'], unique=False)
    op.create_table('memorynote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('source_message_id', sa.Integer(), nullable=True),
    sa.Column('importance_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], ),
    sa.ForeignKeyConstraint(['source_message_id'], ['message.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_memory_importance', 'memorynote', ['character_id', 'importance_score'], unique=False)
    op.create_index(op.f('ix_memorynote_character_id'), 'memorynote', ['character_id'], unique=False)
    op.create_index(op.f('ix_memorynote_conversation_id'), 'memorynote', ['conversation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_memorynote_conversation_id'), table_name='memorynote')
    op.drop_index(op.f('ix_memorynote_character_id'), table_name='memorynote')
    op.drop_index('idx_memory_importance', table_name='memorynote')
    op.drop_table('memorynote')
    op.drop_index(op.f('ix_message_emotion'), table_name='message')
    op.drop_table('message')
    op.drop_index(op.f('ix_conversation_user_id'), table_name='conversation')
    op.drop_index(op.f('ix_conversation_is_active'), table_name='conversation')
    op.drop_index(op.f('ix_conversation_character_id'), table_name='conversation')
    op.drop_index('idx_conversation_activity', table_name='conversation')
    op.drop_table('conversation')
    op.drop_table('user')
    op.drop_index('idx_config_mode', table_name='config')
    op.drop_table('config')
    op.drop_index(op.f('ix_character_name'), table_name='character')
    op.drop_index('idx_character_default', table_name='character')
    op.drop_index('idx_character_active', table_name='character')
    op.drop_table('character')
    # ### end Alembic commands ###
